kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mypvsc
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/mypvsc"


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: mypvsc
---
apiVersion: "apps/v1beta1"
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container 
        image: "nginx"
        imagePullPolicy: "IfNotPresent"
        volumeMounts: 
        - name: localvolume
          mountPath: /var/www/html
      volumes:
      - name: localvolume
        persistentVolumeClaim:
          claimName: example-local-claim